# Generated by Django 2.0.4 on 2018-04-06 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("portal", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="profile", name="birth_date", field=models.DateField(null=True)
        )
    ]
