# Generated by Django 2.0.4 on 2018-04-11 01:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("portal", "0002_auto_20180406_1857")]

    operations = [migrations.AlterModelTable(name="profile", table="profile")]
