# Generated by Django 3.0.8 on 2020-07-10 23:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("places", "0003_auto_20200708_0719"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="rating", unique_together={("place", "author")},
        ),
    ]
