# Generated by Django 3.0.8 on 2020-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0007_auto_20200711_0104"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("places", models.ManyToManyField(to="places.Restaurant")),
            ],
            options={"verbose_name_plural": "categories", "db_table": "category"},
        ),
    ]
