# Generated by Django 3.0.8 on 2020-07-12 01:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0008_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="places",
            field=models.ManyToManyField(related_name="categories", to="places.Restaurant"),
        ),
    ]
