# Generated by Django 3.0.8 on 2020-07-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("places", "0009_auto_20200712_0155"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant", options={"ordering": ["name"]},
        ),
    ]
