# Generated by Django 2.0.2 on 2018-02-06 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snippet', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
            ],
            options={
                'db_table': 'rating',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=17)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18)),
                ('min_party', models.IntegerField()),
                ('max_party', models.IntegerField()),
                ('yelp_link', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'restaurant',
            },
        ),
        migrations.AddField(
            model_name='rating',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Restaurant'),
        ),
    ]
