# Generated by Django 2.0.2 on 2018-02-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rating_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='notes',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
