# Generated by Django 2.0.2 on 2018-02-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_auto_20180206_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='yelp_link',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
