services:
  db:
    image: 'postgres:17-alpine'
    volumes:
      - '/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    restart: unless-stopped
  app:
    image: 'chowist:dev'
    build:
      context: '.'
      dockerfile: './build/django.Dockerfile'
    env_file: './compose/envs/django.env'
    ports:
      - '8000:8000'
    depends_on:
      - db
    restart: unless-stopped
